# Generated by Django 5.0.6 on 2024-06-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_payment_order_items_payment_cart_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_method',
            new_name='stripe_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cart_items',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
