# Generated by Django 5.0.6 on 2024-06-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoupload',
            name='image',
        ),
        migrations.AddField(
            model_name='photoupload',
            name='file',
            field=models.FileField(default='default_file.txt', upload_to='files/'),
            preserve_default=False,
        ),
    ]
