# Generated by Django 5.0.6 on 2024-06-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_photoupload_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoupload',
            name='image',
        ),
        migrations.AddField(
            model_name='photoupload',
            name='title',
            field=models.CharField(default='default.txt', max_length=100),
            preserve_default=False,
        ),
    ]
